// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class DatatestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
   // System.setProperty("webdriver.chrome.driver", "/home/amfabian/dev/chromedriver"); 
   // driver = new ChromeDriver();
    //    js = (JavascriptExecutor) driver;
   // vars = new HashMap<String, Object>();
   WebDriverManager.chromedriver().setup();
   ChromeOptions options = new ChromeOptions();
   options.addArguments("--no-sandbox");
   options.addArguments("--disable-dev-shm-usage");
   options.addArguments("--headless");
   driver = new ChromeDriver(options);
   driver.navigate().to("https://google.com");
   driver.manage().window().maximize();
   driver.manage().timeouts().implicitlyWait(120, TimeUnit.MILLISECONDS);

  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
   @Test
  public void dataTestNotNull() {
    driver.get("http://0.0.0.0:8083/manga/search/digimon");
    driver.manage().window().setSize(new Dimension(1920, 1016));
    {
      WebElement element = driver.findElement(By.cssSelector("pre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("pre"));
      assertTrue(elements.size() > 0);
    }
  } 

  @Test
  public void dataTest() {
    driver.get("http://0.0.0.0:8083/manga/search/isekai");
    driver.manage().window().setSize(new Dimension(1920, 1016));
    {
      WebElement element = driver.findElement(By.cssSelector("pre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("pre"));
      assertTrue(elements.get(0).getText().contains("data"));
    }
  } 

  @Test
  public void userLogin(){
    WebElement searchTxt = driver.findElement(By.name("q"));
    searchTxt.sendKeys("automation");
    WebElement submitBtn = driver.findElement(By.name("btnK"));
    submitBtn.click();
    System.out.println("Current URL is:" + driver.getCurrentUrl());
    assertTrue(driver.getTitle().contains("automation"));
    System.out.println("Current Title is:" + driver.getTitle());
}

 
}
