// Generated by Selenium IDE
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import java.util.concurrent.TimeUnit;
public class SistemaTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @BeforeEach
  
  public void setUp() {
   
   WebDriverManager.chromedriver().setup();
   ChromeOptions options = new ChromeOptions();
   options.addArguments("--no-sandbox");
   options.addArguments("--disable-dev-shm-usage");
   options.addArguments("--headless");
   driver = new ChromeDriver(options);
   driver.navigate().to("https://google.com");
   driver.manage().window().maximize();
   driver.manage().timeouts().implicitlyWait(120, TimeUnit.MILLISECONDS);

  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void googleTest(){
    WebElement searchTxt = driver.findElement(By.name("q"));
    searchTxt.sendKeys("automation");
    WebElement submitBtn = driver.findElement(By.name("btnK"));
    submitBtn.click();
    System.out.println("Current URL is:" + driver.getCurrentUrl());
    assertTrue(driver.getTitle().contains("automation"));
    System.out.println("Current Title is:" + driver.getTitle());
}

@Test
  public void homeTest() {
    driver.get("http://0.0.0.0:8083/");
    driver.manage().window().setSize(new Dimension(1920, 1016));
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.cssSelector("h1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("h1"));
      assertTrue(elements.get(0).getText().contains("Quarkus"));
    }
  }

   @Test
  public void dataTestNotNull() {
    driver.get("http://0.0.0.0:8083/manga/search/digimon");
    driver.manage().window().setSize(new Dimension(1920, 1016));
    {
      WebElement element = driver.findElement(By.cssSelector("pre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("pre"));
      assertTrue(elements.size() > 0);
    }
  } 

  @Test
  public void dataTestTrue() {
    driver.get("http://0.0.0.0:8083/manga/search/isekai");
    driver.manage().window().setSize(new Dimension(1920, 1016));
    {
      WebElement element = driver.findElement(By.cssSelector("pre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("pre"));
      assertTrue(elements.get(0).getText().contains("myanimelist.net"));
    }
  } 

  @Test
  public void dataTestFalse() {
    driver.get("http://0.0.0.0:8083/manga/search/isekai");
    driver.manage().window().setSize(new Dimension(1920, 1016));
    {
      WebElement element = driver.findElement(By.cssSelector("pre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("pre"));
      assertFalse(elements.get(0).getText().contains("saudhausdhuasdhu.net"));
    }
  } 
  
 
}
